---
apiVersion: v1
kind: Namespace
metadata:
  name: unified-ai-frontend
  annotations:
    field.cattle.io/projectId: c-x4kpv:p-rqqdj
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unified-ai-frontend
  name: unified-ai-frontend
  namespace: unified-ai-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unified-ai-frontend
  template:
    metadata:
      labels:
        app: unified-ai-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      hostAliases:
        - hostnames:
          - dev2.gcs.sib
          ip: 10.160.0.3
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - image: ${CICD_REGISTRY}/unified-ai-frontend:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        env:
        - name: APP_ENV
          value: "${APP_ENV}"
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: API_URL
          value: "${API_URL}"
        - name: PUBLIC_URL
          value: "${PUBLIC_URL}"
        - name: NEXT_PUBLIC_APP_ENV
          value: "${APP_ENV}"
        - name: NEXT_PUBLIC_ENABLE_ANALYTICS
          value: "${ENABLE_ANALYTICS}"
        - name: NEXT_PUBLIC_SENTRY_DSN
          value: "${SENTRY_DSN}"
        - name: NEXT_PUBLIC_GTM_ID
          value: "${GTM_ID}"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: next-cache
          mountPath: /.next
      volumes:
      - name: tmp
        emptyDir: {}
      - name: next-cache
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: unified-ai-frontend-service
  namespace: unified-ai-frontend
  labels:
    app: unified-ai-frontend
spec:
  selector:
    app: unified-ai-frontend
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unified-ai-frontend-ingress
  namespace: unified-ai-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - ${INGRESS_HOST}
    secretName: unified-ai-frontend-tls
  rules:
  - host: ${INGRESS_HOST}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unified-ai-frontend-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-ai-frontend-config
  namespace: unified-ai-frontend
data:
  nginx.conf: |
    upstream nextjs_upstream {
        server localhost:3001;
    }
    
    server {
        listen 80;
        server_name _;
        
        # Security headers
        add_header X-Frame-Options "DENY" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        
        # Health check endpoint
        location /health {
            proxy_pass http://nextjs_upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }
        
        # Static assets caching
        location /_next/static/ {
            proxy_pass http://nextjs_upstream;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
        
        # Main application
        location / {
            proxy_pass http://nextjs_upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
            
            # Timeout settings
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
    }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: unified-ai-frontend-hpa
  namespace: unified-ai-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unified-ai-frontend
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80