import { cookies } from 'next/headers'
import '@dtsl/css-design-tokens/dist/index.css'
import '@dtsl/css-design-tokens/dist/themes/brevo/index.css'

import '../globals.css'

export const runtime = 'edge'

export const metadata = {
	title: 'Account Frontend',
	description: 'Generated by brevo',
}

export default async function RootLayout(props) {
	const { children } = props

	const cookieStore = cookies()
	const { value: locale = 'en' } = cookieStore.get('tmpl_lang') || {}

	console.log('#####cookieStore', locale)

	return (
		<html lang={locale}>
			<body>{children}</body>
		</html>
	)
}
